import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SessionManager from "@/components/SessionManager/page";
import { AverageRateProvider } from "../context/AverageRateContext"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-yellow-400">
        <SessionManager />
        <Navbar />
        <AverageRateProvider>
          {children}
        </AverageRateProvider>
      </body>
    </html>
  );
}
