import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useEffect } from "react";
import useLocalStorage from "@/useLocalStorage";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // useEffect(() => {
  //   const control = () => {
  //     const jwtToken = localStorage.getItem("jwtToken");
  //     if (jwtToken) {
  //       return true;
  //     } else {
  //       return false;
  //     }
  //   };
  // }, []);

  const [value] = useLocalStorage("jwtToken", null);
  return (
    <html lang="en">
      <body className="bg-yellow-400">
        <Navbar isAuthenticated={value} />
        {children}
      </body>
    </html>
  );
}
