// layout.tsx
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AverageRateProvider } from "../context/AverageRateContext";
import ClientOnly from "@/components/ClientOnly"; // Yeni client-side bileşen

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-yellow-400">
        <ClientOnly>
          <AverageRateProvider>
            {children}
          </AverageRateProvider>
        </ClientOnly>
      </body>
    </html>
  );
}
